-- Module for question 2
{- Each new term in the Fibonacci sequence is generated by
adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose
values do not exceed four million, find the sum of the even-
valued terms. -}

module Questions.Q2 where

import Data.List

solve:: Int -> Int
solve limit =
    fromInteger (sum evenFib)
        where
            evenFib = [x | x<- fibSeries, x<nLimit, even x]
            fibSeries = takeWhile (<nLimit) fibs
            nLimit = toInteger limit

fibs :: [Integer]
fibs = 1 : 2 : zipWith (+) fibs (tail fibs)

question:: String
question = "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."